targets:
  $default:
    builders:
      built_value_generator:built_value:
        generate_for:
          exclude:
            - test/** # Exclude tests from built_value by default if needed
      mockito:mockBuilder:
        generate_for:
          include:
            - test/**
