name: agentbanking_channel
description: A Flutter project for Agent Banking Channel implementation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  dio: ^5.3.2
  sqflite_sqlcipher: ^3.0.0+1
  path: ^1.8.3
  flutter_secure_storage: ^8.0.0
  geolocator: ^10.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  workmanager: ^0.5.1
  decimal: ^2.3.3
  mockito: ^5.4.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
