// Mocks generated by Mockito 5.4.6 from annotations
// in agentbanking_channel/test/features/merchant/merchant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:agentbanking_channel/features/compliance/providers/compliance_provider.dart'
    as _i6;
import 'package:agentbanking_channel/features/hardware/hardware_interfaces.dart'
    as _i11;
import 'package:agentbanking_channel/features/merchant/models/merchant_models.dart'
    as _i4;
import 'package:agentbanking_channel/features/settlement/models/float_models.dart'
    as _i5;
import 'package:agentbanking_channel/features/settlement/providers/float_provider.dart'
    as _i12;
import 'package:agentbanking_channel/features/transactions/models/transaction_models.dart'
    as _i3;
import 'package:agentbanking_channel/features/transactions/repositories/transaction_repository.dart'
    as _i7;
import 'package:decimal/decimal.dart' as _i10;
import 'package:dio/dio.dart' as _i2;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:state_notifier/state_notifier.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionQuoteResponse_1 extends _i1.SmartFake
    implements _i3.TransactionQuoteResponse {
  _FakeTransactionQuoteResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionExecutionResponse_2 extends _i1.SmartFake
    implements _i3.TransactionExecutionResponse {
  _FakeTransactionExecutionResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRetailSaleResponse_3 extends _i1.SmartFake
    implements _i4.RetailSaleResponse {
  _FakeRetailSaleResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashbackResponse_4 extends _i1.SmartFake
    implements _i4.CashbackResponse {
  _FakeCashbackResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFloatLedger_5 extends _i1.SmartFake implements _i5.FloatLedger {
  _FakeFloatLedger_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComplianceState_6 extends _i1.SmartFake
    implements _i6.ComplianceState {
  _FakeComplianceState_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i7.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i8.Future<_i3.TransactionQuoteResponse> getQuote(
          _i3.TransactionQuoteRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuote,
          [request],
        ),
        returnValue: _i8.Future<_i3.TransactionQuoteResponse>.value(
            _FakeTransactionQuoteResponse_1(
          this,
          Invocation.method(
            #getQuote,
            [request],
          ),
        )),
      ) as _i8.Future<_i3.TransactionQuoteResponse>);

  @override
  _i8.Future<_i3.TransactionExecutionResponse> executeTransaction(
          _i3.TransactionExecutionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeTransaction,
          [request],
        ),
        returnValue: _i8.Future<_i3.TransactionExecutionResponse>.value(
            _FakeTransactionExecutionResponse_2(
          this,
          Invocation.method(
            #executeTransaction,
            [request],
          ),
        )),
      ) as _i8.Future<_i3.TransactionExecutionResponse>);

  @override
  _i8.Future<String> performProxyEnquiry(
    String? proxyId,
    String? proxyType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #performProxyEnquiry,
          [
            proxyId,
            proxyType,
          ],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #performProxyEnquiry,
            [
              proxyId,
              proxyType,
            ],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i3.TransactionExecutionResponse> balanceInquiry(
          _i3.TransactionExecutionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #balanceInquiry,
          [request],
        ),
        returnValue: _i8.Future<_i3.TransactionExecutionResponse>.value(
            _FakeTransactionExecutionResponse_2(
          this,
          Invocation.method(
            #balanceInquiry,
            [request],
          ),
        )),
      ) as _i8.Future<_i3.TransactionExecutionResponse>);

  @override
  _i8.Future<_i3.TransactionExecutionResponse> initiateDuitNow({
    required String? quoteId,
    required String? proxyId,
    required String? proxyType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateDuitNow,
          [],
          {
            #quoteId: quoteId,
            #proxyId: proxyId,
            #proxyType: proxyType,
          },
        ),
        returnValue: _i8.Future<_i3.TransactionExecutionResponse>.value(
            _FakeTransactionExecutionResponse_2(
          this,
          Invocation.method(
            #initiateDuitNow,
            [],
            {
              #quoteId: quoteId,
              #proxyId: proxyId,
              #proxyType: proxyType,
            },
          ),
        )),
      ) as _i8.Future<_i3.TransactionExecutionResponse>);

  @override
  _i8.Future<String> getDuitNowStatus(String? referenceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDuitNowStatus,
          [referenceId],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getDuitNowStatus,
            [referenceId],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i4.RetailSaleResponse> executeRetailSale(
    _i10.Decimal? amount,
    String? fundingSource, {
    String? pinBlock,
    String? cardToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeRetailSale,
          [
            amount,
            fundingSource,
          ],
          {
            #pinBlock: pinBlock,
            #cardToken: cardToken,
          },
        ),
        returnValue:
            _i8.Future<_i4.RetailSaleResponse>.value(_FakeRetailSaleResponse_3(
          this,
          Invocation.method(
            #executeRetailSale,
            [
              amount,
              fundingSource,
            ],
            {
              #pinBlock: pinBlock,
              #cardToken: cardToken,
            },
          ),
        )),
      ) as _i8.Future<_i4.RetailSaleResponse>);

  @override
  _i8.Future<_i4.CashbackResponse> executeCashback(
    _i10.Decimal? purchaseAmount,
    _i10.Decimal? cashbackAmount,
    String? fundingSource, {
    String? pinBlock,
    String? cardToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeCashback,
          [
            purchaseAmount,
            cashbackAmount,
            fundingSource,
          ],
          {
            #pinBlock: pinBlock,
            #cardToken: cardToken,
          },
        ),
        returnValue:
            _i8.Future<_i4.CashbackResponse>.value(_FakeCashbackResponse_4(
          this,
          Invocation.method(
            #executeCashback,
            [
              purchaseAmount,
              cashbackAmount,
              fundingSource,
            ],
            {
              #pinBlock: pinBlock,
              #cardToken: cardToken,
            },
          ),
        )),
      ) as _i8.Future<_i4.CashbackResponse>);

  @override
  _i8.Future<String> getComplianceStatus() => (super.noSuchMethod(
        Invocation.method(
          #getComplianceStatus,
          [],
        ),
        returnValue: _i8.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getComplianceStatus,
            [],
          ),
        )),
      ) as _i8.Future<String>);
}

/// A class which mocks [ICardReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockICardReader extends _i1.Mock implements _i11.ICardReader {
  MockICardReader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i11.CardData?> readCard() => (super.noSuchMethod(
        Invocation.method(
          #readCard,
          [],
        ),
        returnValue: _i8.Future<_i11.CardData?>.value(),
      ) as _i8.Future<_i11.CardData?>);
}

/// A class which mocks [IPinPad].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPinPad extends _i1.Mock implements _i11.IPinPad {
  MockIPinPad() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> isAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isAvailable,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<String?> capturePin() => (super.noSuchMethod(
        Invocation.method(
          #capturePin,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);
}

/// A class which mocks [FloatNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockFloatNotifier extends _i1.Mock implements _i12.FloatNotifier {
  MockFloatNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<_i5.FloatLedger> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i5.FloatLedger>.empty(),
      ) as _i8.Stream<_i5.FloatLedger>);

  @override
  _i5.FloatLedger get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeFloatLedger_5(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.FloatLedger);

  @override
  _i5.FloatLedger get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeFloatLedger_5(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i5.FloatLedger);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  set onError(_i13.ErrorListener? value) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set state(_i5.FloatLedger? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> fetchLatestBalance() => (super.noSuchMethod(
        Invocation.method(
          #fetchLatestBalance,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool updateShouldNotify(
    _i5.FloatLedger? old,
    _i5.FloatLedger? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i13.RemoveListener addListener(
    _i14.Listener<_i5.FloatLedger>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i13.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ComplianceNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockComplianceNotifier extends _i1.Mock
    implements _i6.ComplianceNotifier {
  MockComplianceNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<_i6.ComplianceState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i8.Stream<_i6.ComplianceState>.empty(),
      ) as _i8.Stream<_i6.ComplianceState>);

  @override
  _i6.ComplianceState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeComplianceState_6(
          this,
          Invocation.getter(#state),
        ),
      ) as _i6.ComplianceState);

  @override
  _i6.ComplianceState get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeComplianceState_6(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i6.ComplianceState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  set onError(_i13.ErrorListener? value) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set state(_i6.ComplianceState? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void freeze(String? reason) => super.noSuchMethod(
        Invocation.method(
          #freeze,
          [reason],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unlock() => super.noSuchMethod(
        Invocation.method(
          #unlock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> simulateWebhookUnlock() => (super.noSuchMethod(
        Invocation.method(
          #simulateWebhookUnlock,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool updateShouldNotify(
    _i6.ComplianceState? old,
    _i6.ComplianceState? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i13.RemoveListener addListener(
    _i14.Listener<_i6.ComplianceState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i13.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
