// Mocks generated by Mockito 5.4.6 from annotations
// in agentbanking_channel/test/core/offline/offline_queue_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:agentbanking_channel/core/security/secure_storage_manager.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SecureStorageManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageManager extends _i1.Mock
    implements _i2.SecureStorageManager {
  MockSecureStorageManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveJwt(String? jwt) => (super.noSuchMethod(
        Invocation.method(
          #saveJwt,
          [jwt],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearJwt() => (super.noSuchMethod(
        Invocation.method(
          #clearJwt,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> readJwt() => (super.noSuchMethod(
        Invocation.method(
          #readJwt,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setComplianceLock(bool? isLocked) => (super.noSuchMethod(
        Invocation.method(
          #setComplianceLock,
          [isLocked],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> getComplianceLocked() => (super.noSuchMethod(
        Invocation.method(
          #getComplianceLocked,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String> getSqlCipherPassphrase() => (super.noSuchMethod(
        Invocation.method(
          #getSqlCipherPassphrase,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getSqlCipherPassphrase,
            [],
          ),
        )),
      ) as _i3.Future<String>);
}
