// Mocks generated by Mockito 5.4.6 from annotations
// in agentbanking_channel/test/features/settlement/settlement_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:agentbanking_channel/features/merchant/models/merchant_models.dart'
    as _i4;
import 'package:agentbanking_channel/features/transactions/models/transaction_models.dart'
    as _i3;
import 'package:agentbanking_channel/features/transactions/repositories/transaction_repository.dart'
    as _i5;
import 'package:decimal/decimal.dart' as _i8;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionQuoteResponse_1 extends _i1.SmartFake
    implements _i3.TransactionQuoteResponse {
  _FakeTransactionQuoteResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionExecutionResponse_2 extends _i1.SmartFake
    implements _i3.TransactionExecutionResponse {
  _FakeTransactionExecutionResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRetailSaleResponse_3 extends _i1.SmartFake
    implements _i4.RetailSaleResponse {
  _FakeRetailSaleResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCashbackResponse_4 extends _i1.SmartFake
    implements _i4.CashbackResponse {
  _FakeCashbackResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i5.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i6.Future<_i3.TransactionQuoteResponse> getQuote(
          _i3.TransactionQuoteRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuote,
          [request],
        ),
        returnValue: _i6.Future<_i3.TransactionQuoteResponse>.value(
            _FakeTransactionQuoteResponse_1(
          this,
          Invocation.method(
            #getQuote,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.TransactionQuoteResponse>);

  @override
  _i6.Future<_i3.TransactionExecutionResponse> executeTransaction(
          _i3.TransactionExecutionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeTransaction,
          [request],
        ),
        returnValue: _i6.Future<_i3.TransactionExecutionResponse>.value(
            _FakeTransactionExecutionResponse_2(
          this,
          Invocation.method(
            #executeTransaction,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.TransactionExecutionResponse>);

  @override
  _i6.Future<String> performProxyEnquiry(
    String? proxyId,
    String? proxyType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #performProxyEnquiry,
          [
            proxyId,
            proxyType,
          ],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #performProxyEnquiry,
            [
              proxyId,
              proxyType,
            ],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i3.TransactionExecutionResponse> balanceInquiry(
          _i3.TransactionExecutionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #balanceInquiry,
          [request],
        ),
        returnValue: _i6.Future<_i3.TransactionExecutionResponse>.value(
            _FakeTransactionExecutionResponse_2(
          this,
          Invocation.method(
            #balanceInquiry,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.TransactionExecutionResponse>);

  @override
  _i6.Future<_i3.TransactionExecutionResponse> initiateDuitNow({
    required String? quoteId,
    required String? proxyId,
    required String? proxyType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateDuitNow,
          [],
          {
            #quoteId: quoteId,
            #proxyId: proxyId,
            #proxyType: proxyType,
          },
        ),
        returnValue: _i6.Future<_i3.TransactionExecutionResponse>.value(
            _FakeTransactionExecutionResponse_2(
          this,
          Invocation.method(
            #initiateDuitNow,
            [],
            {
              #quoteId: quoteId,
              #proxyId: proxyId,
              #proxyType: proxyType,
            },
          ),
        )),
      ) as _i6.Future<_i3.TransactionExecutionResponse>);

  @override
  _i6.Future<String> getDuitNowStatus(String? referenceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDuitNowStatus,
          [referenceId],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getDuitNowStatus,
            [referenceId],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i4.RetailSaleResponse> executeRetailSale(
    _i8.Decimal? amount,
    String? fundingSource, {
    String? pinBlock,
    String? cardToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeRetailSale,
          [
            amount,
            fundingSource,
          ],
          {
            #pinBlock: pinBlock,
            #cardToken: cardToken,
          },
        ),
        returnValue:
            _i6.Future<_i4.RetailSaleResponse>.value(_FakeRetailSaleResponse_3(
          this,
          Invocation.method(
            #executeRetailSale,
            [
              amount,
              fundingSource,
            ],
            {
              #pinBlock: pinBlock,
              #cardToken: cardToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.RetailSaleResponse>);

  @override
  _i6.Future<_i4.CashbackResponse> executeCashback(
    _i8.Decimal? purchaseAmount,
    _i8.Decimal? cashbackAmount,
    String? fundingSource, {
    String? pinBlock,
    String? cardToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeCashback,
          [
            purchaseAmount,
            cashbackAmount,
            fundingSource,
          ],
          {
            #pinBlock: pinBlock,
            #cardToken: cardToken,
          },
        ),
        returnValue:
            _i6.Future<_i4.CashbackResponse>.value(_FakeCashbackResponse_4(
          this,
          Invocation.method(
            #executeCashback,
            [
              purchaseAmount,
              cashbackAmount,
              fundingSource,
            ],
            {
              #pinBlock: pinBlock,
              #cardToken: cardToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.CashbackResponse>);

  @override
  _i6.Future<String> getComplianceStatus() => (super.noSuchMethod(
        Invocation.method(
          #getComplianceStatus,
          [],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getComplianceStatus,
            [],
          ),
        )),
      ) as _i6.Future<String>);
}
